export {
  btnOutline,
  btnPrimary,
  Field,
  fieldClass,
  FormSection,
  formPageWrap,
  formStickyFooter,
  formToolbar,
  labelClass,
  pageToolbar,
  tableHeadClass,
  tableScrollShell,
  thClass,
} from "../Section/sectionShared";
